# fly.toml file generated for linguagens-lavor on 2023-04-02T08:26:08-03:00

app = "linguagens-lavor"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gig"
processes = []

[build]
  image = "jacquelineoliveira/linguagensapi:latest"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
